name: hackathon_smartvow
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  shimmer: ^3.0.0
  web3dart: ^2.7.3
  reown_appkit: ^1.5.0
  http: ^1.2.0

  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  freezed: ^3.2.0
  json_serializable: ^6.11.2
  riverpod_generator: ^3.0.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
